### ISSUE TITLE
Header Block: Menu links to `<nolink>` instead of preventing linking

### ISSUE THREAD

**Issue by allsite** [backdrop-contrib/special_menu_items#21]
My links are going to ``mysite.com/<nolink>``. The expected behavior is nothing would happen when clicked.

**Comment by laryn** [comment]
Hi @allsite -- is this using the latest version? And is it linking for you on the front end or in the admin panel?

**Comment by argiepiano** [comment]
I can confirm this behavior, but in the Breadcrumbs rather than in the  Primary Navigation. The Primary Navigation correctly links to `/#`. However, on the breadcrumbs of the front end shown when you visit a page below the Special Menu Item, the link is shown as `/<nolink>` 

I'm using version 1.x-2.1.2

**Comment by laryn** [comment]
I haven't had a chance to look into this, but dug far enough to see that breadcrumbs have come up before in this module's history. Maybe this thread is useful:

 - https://www.drupal.org/node/573034

**Comment by argiepiano** [comment]
@laryn yes, it looks like a similar problem has come up before in Drupal. The patch in the thread you sent was for version 7.x-1.0  (Drupal) of the module. That version took care of fixing the breadcrumb issue within an implementation of hook_init().  Version 7.x-2.0 of the module removed that hook_init() implementation as seen [here](https://www.drupal.org/project/special_menu_items/issues/2234319).   I'll dig a bit to see how version 7.x-2.0 solved this issue without hook_init.

**Comment by argiepiano** [comment]
After digging a bit I found the issue. 

- Drupal's version 2 module used `hook_theme_registry_alter` to modify the theme registry for `theme_link`. The modified registry made a call to a custom, rewritten function called `special_menu_items_link` (instead of calling the core function `theme_link`). This new function took care of removing the `<nolink>` link from both menu items AND links. 
- Backdrop, instead, modified the theme registry for `theme_menu_link` (not `theme_link`) to invoke its custom function to take care of `<nolink>`. The issue with that is that this custom function is only invoked when theming menu links, as opposed to ALL links in the Drupal vesion.

Given the differences in theme hooks between Drupal and Backdrop (e.g. the absence of preprocess functions in Backdrop) I believe the best course of action for Backdrop is to rewrite the registry to override both: theme_menu_link and theme_breadcrumb. 

I'll work on a patch for this.

**Comment by argiepiano** [comment]
I have started a new issue (#22) specifically for this problem with breadcrumbs. I will be submitting a pull request soon.

**Comment by allsite** [comment]
I did some more testing. The issue seems to also occur in a case the menu is inside the Header layout block. Adding a Menu block to the Header region functions as expected. However adding a Header block to the Header region (with the menu in question selected), then clicking a "no link" menu item results in the following.

The requested page "/%3Cnolink%3E" could not be found.

![image](https://user-images.githubusercontent.com/6035778/133019889-e9ca4f2a-7113-45f3-81fe-dd5a61a2c19a.jpeg)

**Comment by laryn** [comment]
@allsite I can confirm the behavior. I'm not sure when I'll be able to look at it but if you can provide a PR I can review.

**Comment by argiepiano** [comment]
@allsite, I've been digging a bit to see why this happens. 

First of all, please notice that the Header block's menu can't be normally shown as a dropdown menu. Rather, it's  always a "Top level only" type of menu (unless I'm missing something). Therefore the  Special Menu Items that are on the top level of the Header block menu will normally not generate a dropdown, and, without this but, they would basically do nothing when clicked.  So, those Special Menu Items on top of the Header block menu become rather useless, since they can't fulfill their original purpose of opening up the children below them when hovering over them. Still, having them show as `/<nolink>` is definitely not desirable.

The reason why they show as `<nolink>` is that the Header block menu uses `theme_links` to theme those menu links. The module Special Menu Items does not deal with `theme_links` at all. What it does, is, it "hijacks" `theme_menu_link` directly from the theme registry to get rid of `<nolink>` -- a theme function that the Header block menus never use for rendering them.

So, a possible solution: add some code to `special_menu_items_theme_registry_alter()` to "hijack" the function `theme_links` the same way it does with `theme_menu_link`, and then add code similar to `special_menu_items_link()` to rewrite the `<nolink>`.

Alternatively (and possibly easier and less harmful), it may be possible to implement of `template_preprocess_header()` within the module to take care of those.

Let me know if you prefer not to try any of the above and I can try something myself.

**Comment by argiepiano** [comment]
Added a PR for a possible solution to this issue.

**Comment by laryn** [comment]
@allsite Are you able to test this with the site that was giving you the problem?

**Comment by allsite** [comment]
@laryn I'd be happy to. Can you recommend a process for applying the PR? I'm a bit new to this :)

**Comment by argiepiano** [comment]
@allsite, there are different ways of applying patches manually. The accepted answer in this [page](https://drupal.stackexchange.com/questions/23347/how-do-i-apply-a-patch-file) contains several links.

Perhaps the easiest way is:
1. Back up the folder `special_menu_items` in the `modules` folder of your Backdrop installation. Typically you also want to back up your database and your configuration folder. 
2. Download the patch or diff file. The commit for my patch is located [here](https://github.com/backdrop-contrib/special_menu_items/commit/a1a04b528661748678e60f183f023b69fb23e485), but the easiest way to download that as a diff file is to simply add ".diff" at the end of the URL, like [here](https://github.com/backdrop-contrib/special_menu_items/commit/a1a04b528661748678e60f183f023b69fb23e485.diff)
2. The last link above will show you a txt file in your browser. Simply save that file directly from the browser into the `special_menu_items folder`, which is most likely in your `modules` folder of your Backdrop installation. Be sure the file extension is .diff, not .txt
3. If you have a Mac, open Terminal and navigate to that folder
4. Run `patch -p1 < a1a04b528661748678e60f183f023b69fb23e485.diff`. This Linux command will apply the patch to the correct file
5. If you have a Windows machine... see the links above. I'm not familiar with ways in which you can manually apply patches on Windows

Once the patch is applied **be sure to clear all caches in Backdrop** in order for the new hooks to run.

You may want to revert to the original files after testing. You can do so by restoring the backed up files for `special_menu_items` and **clearing the caches again**.

**Comment by allsite** [comment]
@argiepiano these instructions were very helpful, thank you. 

@laryn 
I applied the patch per step 5. The link still went to ``/<nolink>``. Then I realized my test site was using Bootstrap, which has known issues with Layouts and how the header is generated. I switched to Basis and the link now points to ``/node``. I've cleared cache and recreated the menu item. 

Update: I did inspect special_menu_items.module to ensure the patch was applied.

**Comment by argiepiano** [comment]
@allsite, the reason the patch doesn't work with Bootstrap, is that Bootstrap might be overwriting the function `theme_links` or skipping it altogehter.

As for Basis, yes, that's the expected behavior. The `</nolink>` is replaced by the current path -- in your case `/node`, because you are probably on the home page of your site when you clicked the Special Menu Item. Please understand that Special Menu Items have in fact no destinations, so as a compromise, the patch directs them to the current page being viewed. As I mentioned above, the Header Block menus are all "1st level" only, meaning that a Special Menu Item displayed in the Block Header menu will never produce a dropdown. That's just not possible, as it's coded this way in core.

So, if you still want a dropdown to be displayed in the location of the Header Block menu, you'll have to play around with CSS, templates and blocks.

@laryn, I'm not sure if it's worth committing the PR for this, given the limitations of the behavior for Header Block  menus.

**Comment by allsite** [comment]
@laryn Noted that is the expected behavior and there's little use case for nolink in the header block, given the core limitation with that menu. Whether it's worth it or not is perhaps a question of how many others may submit a similar issue. I'm going to close this out and thank you for your attention.

**Comment by laryn** [comment]
I've tried to summarize and link here in the Wiki in case the question arises again in the future:

 - https://github.com/backdrop-contrib/special_menu_items/wiki

Does that look like a reasonable summary? @argiepiano can you spot check the "Performance implications" section as well? That was copied and pasted from the Drupal version -- does it still relate after your recent work?

**Comment by argiepiano** [comment]
@laryn, thanks for summarizing in the wiki. That part looks good. 

Regarding the section about performance implications: that information is outdated. The Drupal version of Special Menu Items did rewrite `theme_link()`, but the Backdrop version uses `theme_menu_link` instead, which is a different theming function, and is used only for theming the menu links and submenus. See [lines 138 and 139](https://github.com/backdrop-contrib/special_menu_items/blob/caf091005e5386a10dcefd62db3eb13055b820b1/special_menu_items.module#L138-L139) in Backdrop's version of the module. Therefore, all information in the wiki about `l()` is incorrect (`l` was only affected when the Drupal version used `theme_link`).

If you want I can rewrite that section of the wiki. Let me know.

**Comment by laryn** [comment]
> If you want I can rewrite that section of the wiki. Let me know.

@argiepiano That would be great -- thank you!

**Comment by argiepiano** [comment]
@laryn, I've edited the wiki. I deleted all references to `theme_link` since the Backdrop version of the module uses `theme_menu_link`. This also means that I had to delete all references to `l()` and the ability to disable `theme_link` with a variable within `settings.php` (a feature which, by the way, was actually removed in the Backdrop version of `theme_link`). So, most of the information in the wiki did not apply to the current version of the module.

**Comment by laryn** [comment]
Thank you for going through that @argiepiano -- much appreciated!

**Comment by argiepiano** [comment]
One additional comment about the PR and patch I submitted (which we decided not to commit): it generates some notices in cases when items are passed to theme_links that do not contain an 'href' key. This happens, for example, when you are previewing a View. If this patch is ever applied, the code inside function `special_menu_items_links` should be checking that the key 'href' is set for each of the passed links.

**Comment by nattywebdev** [comment]
I am experiencing this same issue when adding a 'Text with no link' top menu item to an admin menu I am using for users with an 'editor' role. This is shown (via administration menu source) as the black admin bar for those users.

Is there a reason why the PR mentioned above wasn't committed? Is there a workaround if so?

**Comment by nattywebdev** [comment]
I'm here again finding this is still an issue. Although this issue has been closed, the current version of special_menu_items still exhibits this same behaviour. Am I missing something?

**Comment by argiepiano** [comment]
@nattywebdev, this module hijacks a theming function that may not be used by your active theme. What theme are you using? In short, this module may not work in all themes, and in all menus.

**Comment by argiepiano** [comment]
Also, the module may not work for header menus, since they don't show children by default and the header menu uses a different theming function for the links. Perhaps if you provide more details, we could determine if this is a bug?

**Comment by nattywebdev** [comment]
@argiepiano I use (almost always) a subtheme of Bootstrap5_lite. The use case is an admin menu for 'editor' users, selected using Administration Menu Source (so it appears as that user's administration menu).
When I add one or more child items below the top-level parent and set that top level menu item using 'Text with no link', the menu item has a path assigned which is <nolink> as you can see with the generated html:
```
<a href="/%3Cnolink%3E" class="nolink">
  <span class="admin-bar-link-icon"></span>
  <span class="admin-bar-link-text">List content</span>
</a>
```
My workaround is to simply set the top-level menu item to have the path to the first of the child items.

Any advice welcomed!

**Comment by argiepiano** [comment]
Unfortunately `admin_bar`, which takes care of theming the administration menu links, uses `l()` to generate the links. This effectively bypasses this module's theming functions, resulting in this problem.

There is no easy workaround. This module would need to be rewritten completely to adjust. And, to make things worse, in Backdrop `l()` does not call any theming function (in Drupal `l()` calls `theme_link()`, in Backdrop this is the other way around, effectively making it so much more difficult to override the theming of links produced with `l()`).

**Comment by nattywebdev** [comment]
Thanks for taking the time to explain, @argiepiano  .  Not a bug then, but effectively by design and a consequence of how I was trying to use the module on the admin menu. Maybe I can suggest it be added to the description of the module? Or is that what is meant by the comment about use in a header block?

**Comment by argiepiano** [comment]
Actually, there may be an easy way to take care of these situations: writing a small javascript file that looks for `<nolink>` and replaces it with `#`. This would only work on browsers that have js enabled (which nowadays is pretty much everyone). @laryn, what do you think? This would be a "last resource" solution for those situations where server side theming of the links did not run.

**Comment by laryn** [comment]
@argiepiano Interesting idea. Would it be worth adding a toggle in `admin/config/system/special_menu_items` to "Add Javascript to replace..." (exact language TBD) so that people who need this could turn it on, but people who don't need it don't get the cruft inserted in their site? There could potentially even be a description under the toggle that explains which types of menus don't work by default.

**Comment by argiepiano** [comment]
@laryn, I think that's a great idea. I can try tonight a POC PR
